# Generated by Django 3.2.5 on 2021-07-21 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DopeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите своё имя', max_length=20)),
                ('nickname', models.CharField(help_text='Введите свой никнейм', max_length=20)),
                ('description', models.TextField(help_text='Расскажите о себе')),
                ('photo', models.FileField(upload_to='')),
                ('status', models.CharField(blank=True, choices=[('v', 'Visible'), ('h', 'Hidden')], default='v', help_text='Видимость аккаунта', max_length=1)),
            ],
            options={
                'verbose_name': '',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk', models.CharField(blank=True, help_text='Профиль Вконтакте', max_length=30, null=True)),
                ('fb', models.CharField(blank=True, help_text='Профиль Facebook', max_length=30, null=True)),
                ('instagram1', models.CharField(blank=True, help_text='Профиль Instagram', max_length=30, null=True, verbose_name='Instagram')),
                ('instagram2', models.CharField(blank=True, help_text='Профиль Instagram', max_length=30, null=True, verbose_name='Instagram 2')),
                ('tiktok', models.CharField(blank=True, help_text='Профиль Tik-Tok', max_length=30, null=True)),
                ('twitter', models.CharField(blank=True, help_text='Профиль Twitter', max_length=30, null=True)),
                ('snapchat', models.CharField(blank=True, help_text='Профиль Snapchat', max_length=30, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.dopeuser')),
            ],
        ),
    ]
