# Generated by Django 3.2.5 on 2021-07-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dopeuser',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Введите дату своего рождения в формате YYYY-MM-DD', null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='dopeuser',
            name='description',
            field=models.TextField(blank=True, help_text='Расскажите о себе', max_length=500, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='dopeuser',
            name='nickname',
            field=models.CharField(blank=True, help_text='Введите свой никнейм', max_length=20, null=True, verbose_name='nickname'),
        ),
        migrations.AlterField(
            model_name='dopeuser',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='photo'),
        ),
    ]
