# Generated by Django 3.2.5 on 2021-07-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dopeuser',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='dopeuser',
            name='description',
            field=models.TextField(blank=True, help_text='Расскажите о себе', null=True),
        ),
        migrations.AlterField(
            model_name='dopeuser',
            name='nickname',
            field=models.CharField(blank=True, help_text='Введите свой никнейм', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dopeuser',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
