# Generated by Django 3.2.5 on 2021-07-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20210721_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='dopeuser',
            name='lastname',
            field=models.CharField(blank=True, help_text='Введите свою фамилию', max_length=20, null=True),
        ),
    ]
