# Generated by Django 3.2.5 on 2021-08-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_dopeuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dopeuser',
            options={'ordering': ['user']},
        ),
        migrations.RemoveField(
            model_name='dopeuser',
            name='nickname',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='dopeuser',
            name='status',
            field=models.CharField(blank=True, choices=[('v', 'Visible'), ('h', 'Hidden')], default='v', help_text='Видимость аккаунта', max_length=1, verbose_name='visible status'),
        ),
    ]
