# Generated by Django 3.2.5 on 2021-07-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20210729_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dopeuser',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Введите дату своего рождения', null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='messengers',
            name='facebook_messenger',
            field=models.CharField(blank=True, help_text='Укажите никнейм Facebook Messenger', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='messengers',
            name='viber',
            field=models.CharField(blank=True, help_text='Укажите номер Viber', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='messengers',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Укажите номер WhatsApp', max_length=50, null=True),
        ),
    ]
