# Generated by Django 3.2.5 on 2021-08-17 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20210808_1026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dopeuser',
            options={'ordering': ['user'], 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
