# Generated by Django 3.2.5 on 2021-07-21 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_dopeuser_lastname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersocialmedia',
            old_name='fb',
            new_name='facebook',
        ),
    ]
