# Generated by Django 3.2.5 on 2021-07-21 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_rename_fb_usersocialmedia_facebook'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersocialmedia',
            options={'ordering': ['id']},
        ),
    ]
