# Generated by Django 3.2.5 on 2021-08-17 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_dopeuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gaming',
            options={'ordering': ['user'], 'verbose_name': 'Игры', 'verbose_name_plural': 'Игры'},
        ),
        migrations.AlterModelOptions(
            name='maps',
            options={'ordering': ['user'], 'verbose_name': 'Карты', 'verbose_name_plural': 'Карты'},
        ),
        migrations.AlterModelOptions(
            name='messengers',
            options={'ordering': ['user'], 'verbose_name': 'Мессенджер', 'verbose_name_plural': 'Мессенджеры'},
        ),
        migrations.AlterModelOptions(
            name='musicplatforms',
            options={'ordering': ['user'], 'verbose_name': 'Музыка', 'verbose_name_plural': 'Музыка'},
        ),
        migrations.AlterModelOptions(
            name='other',
            options={'ordering': ['user'], 'verbose_name': 'Другое', 'verbose_name_plural': 'Другое'},
        ),
        migrations.AlterModelOptions(
            name='personalcontacts',
            options={'ordering': ['user'], 'verbose_name': 'Персональные контакты'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['user'], 'verbose_name': 'Портфолио', 'verbose_name_plural': 'Портфолио'},
        ),
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'ordering': ['user'], 'verbose_name': 'Социальная сеть', 'verbose_name_plural': 'Социальные сети'},
        ),
        migrations.AlterModelOptions(
            name='videocallservices',
            options={'ordering': ['user'], 'verbose_name': 'Видеосвязь', 'verbose_name_plural': 'Video Call Services'},
        ),
        migrations.AlterModelOptions(
            name='videohostings',
            options={'ordering': ['user'], 'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.AlterModelOptions(
            name='wallets',
            options={'ordering': ['user'], 'verbose_name': 'Кошелёк', 'verbose_name_plural': 'Кошельки'},
        ),
    ]
