# Generated by Django 3.2.5 on 2021-07-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_alter_usersocialmedia_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dopeuser',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='dopeuser',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='dopeuser',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Введите дату своего рождения', null=True),
        ),
    ]
