# Generated by Django 3.2.5 on 2021-08-17 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20210817_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalcontacts',
            options={'ordering': ['user'], 'verbose_name': 'Персональные контакты', 'verbose_name_plural': 'Персональные контакты'},
        ),
        migrations.AlterModelOptions(
            name='videocallservices',
            options={'ordering': ['user'], 'verbose_name': 'Видеосвязь', 'verbose_name_plural': 'Видеосвязь'},
        ),
        migrations.AlterModelOptions(
            name='videohostings',
            options={'ordering': ['user'], 'verbose_name': 'Видео Хостинг', 'verbose_name_plural': 'Видео Хостинг'},
        ),
    ]
