# Generated by Django 3.2.5 on 2021-07-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20210721_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersocialmedia',
            old_name='instagram1',
            new_name='instagram',
        ),
        migrations.AlterField(
            model_name='dopeuser',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Введите дату своего рождения в формате YYYY-MM-DD', null=True),
        ),
    ]
