# Generated by Django 3.2.5 on 2021-07-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20210721_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersocialmedia',
            name='clubhouse',
            field=models.CharField(blank=True, help_text='Профиль Clubhouse', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='usersocialmedia',
            name='odnoklassniki',
            field=models.CharField(blank=True, help_text='Профиль Одноклассники', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='usersocialmedia',
            name='pinterest',
            field=models.CharField(blank=True, help_text='Профиль Pinterest', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='usersocialmedia',
            name='tumblr',
            field=models.CharField(blank=True, help_text='Профиль Tumblr', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='usersocialmedia',
            name='yandex_dzen',
            field=models.CharField(blank=True, help_text='Профиль Яндекс.Дзен', max_length=30, null=True),
        ),
    ]
