# Generated by Django 3.2.5 on 2021-07-21 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_auto_20210721_2135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersocialmedia',
            options={'ordering': ['user']},
        ),
        migrations.CreateModel(
            name='PersonalContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, help_text='Введите номер телефона', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, help_text='Введите свой e-mail', max_length=254, null=True)),
                ('site', models.CharField(blank=True, help_text='Укажите адрес сайта', max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.dopeuser')),
            ],
            options={
                'ordering': ['user'],
            },
        ),
    ]
