# Generated by Django 3.2.5 on 2021-07-21 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_auto_20210721_2254'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSocialMedia',
            new_name='SocialMedia',
        ),
        migrations.AlterModelOptions(
            name='personalcontacts',
            options={'ordering': ['user'], 'verbose_name_plural': 'Personal Contacts'},
        ),
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'ordering': ['user'], 'verbose_name_plural': 'Social Media'},
        ),
    ]
