# Generated by Django 3.2.5 on 2021-07-21 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_messengers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messengers',
            name='facebook_messenger',
            field=models.CharField(blank=True, help_text='Укажите номер или никнейм Facebook Messenger', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='messengers',
            name='telegram',
            field=models.CharField(blank=True, help_text='Укажите номер или никнейм Telegram', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='messengers',
            name='viber',
            field=models.CharField(blank=True, help_text='Укажите номер или никнейм Viber', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='messengers',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Укажите номер или никнейм WhatsApp', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personalcontacts',
            name='email',
            field=models.EmailField(blank=True, help_text='Введите e-mail', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personalcontacts',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Введите номер телефона', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='clubhouse',
            field=models.CharField(blank=True, help_text='Профиль Clubhouse', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='facebook',
            field=models.CharField(blank=True, help_text='Профиль Facebook', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='instagram',
            field=models.CharField(blank=True, help_text='Профиль Instagram', max_length=50, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='instagram2',
            field=models.CharField(blank=True, help_text='Профиль Instagram', max_length=50, null=True, verbose_name='Instagram 2'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='odnoklassniki',
            field=models.CharField(blank=True, help_text='Профиль Одноклассники', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='pinterest',
            field=models.CharField(blank=True, help_text='Профиль Pinterest', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='snapchat',
            field=models.CharField(blank=True, help_text='Профиль Snapchat', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='tiktok',
            field=models.CharField(blank=True, help_text='Профиль Tik-Tok', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='tumblr',
            field=models.CharField(blank=True, help_text='Профиль Tumblr', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='twitter',
            field=models.CharField(blank=True, help_text='Профиль Twitter', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='vk',
            field=models.CharField(blank=True, help_text='Профиль Вконтакте', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='yandex_dzen',
            field=models.CharField(blank=True, help_text='Профиль Яндекс.Дзен', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Wallets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sberbank', models.CharField(blank=True, help_text='Укажите номер карты или номер телефона, к которому привязана карта Сбербанк', max_length=100, null=True)),
                ('alfabank', models.CharField(blank=True, help_text='Укажите номер карты или номер телефона, к которому привязана карта Альфа-Банк', max_length=100, null=True)),
                ('tinkoff', models.CharField(blank=True, help_text='Укажите номер карты или номер телефона, к которому привязана карта Тинькофф Банк', max_length=100, null=True)),
                ('yoomoney', models.CharField(blank=True, help_text='Укажите номер кошелька YooMoney (Яндекс.Деньги', max_length=100, null=True)),
                ('vk_pay', models.CharField(blank=True, help_text='Укажите номер кошелька VK Pay', max_length=100, null=True)),
                ('paypal', models.CharField(blank=True, help_text='Укажите номер кошелька PayPal', max_length=100, null=True)),
                ('qiwi', models.CharField(blank=True, help_text='Укажите номер кошелька QIWI', max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.dopeuser')),
            ],
            options={
                'verbose_name_plural': 'Wallets',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='VideoHostings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube', models.CharField(blank=True, help_text='Профиль/канал Youtube', max_length=50, null=True)),
                ('vimeo', models.CharField(blank=True, help_text='Профиль Vimeo', max_length=50, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.dopeuser')),
            ],
            options={
                'verbose_name_plural': 'Video Hostings',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='VideoCallServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facetime', models.CharField(blank=True, help_text='Укажите номер телефона или логин FaceTime', max_length=50, null=True)),
                ('skype', models.CharField(blank=True, help_text='Укажите логин Skype', max_length=50, null=True)),
                ('zoom', models.CharField(blank=True, help_text='Укажите логин Zoom', max_length=50, null=True)),
                ('discord', models.CharField(blank=True, help_text='Профиль Discord', max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.dopeuser')),
            ],
            options={
                'verbose_name_plural': 'Video Call Services',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behance', models.CharField(blank=True, help_text='Укажите свой профиль Behance', max_length=100, null=True)),
                ('dribbble', models.CharField(blank=True, help_text='Укажите свой профиль Dribbble', max_length=100, null=True)),
                ('500px', models.CharField(blank=True, help_text='Укажите свой профиль 500px', max_length=100, null=True)),
                ('flickr', models.CharField(blank=True, help_text='Укажите свой профиль Flickr', max_length=100, null=True)),
                ('linkedin', models.CharField(blank=True, help_text='Укажите свой профиль LinkedIn', max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.dopeuser')),
            ],
            options={
                'verbose_name_plural': 'Portfolio',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onlyfans', models.CharField(blank=True, help_text='Профиль OnlyFans', max_length=50, null=True)),
                ('podcasts', models.CharField(blank=True, help_text='Профиль Podcasts', max_length=50, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.dopeuser')),
            ],
            options={
                'verbose_name_plural': 'Other',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='MusicPlatforms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apple_music', models.CharField(blank=True, help_text='Профиль Apple Music', max_length=50, null=True)),
                ('spotify', models.CharField(blank=True, help_text='Профиль Spotify', max_length=50, null=True)),
                ('soundcloud', models.CharField(blank=True, help_text='Профиль SoundCloud', max_length=50, null=True)),
                ('yandex_music', models.CharField(blank=True, help_text='Профиль Яндекс.Музыка', max_length=50, null=True)),
                ('vk_boom', models.CharField(blank=True, help_text='Профиль VK BOOM', max_length=50, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.dopeuser')),
            ],
            options={
                'verbose_name_plural': 'Music Platforms',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yandex_maps', models.CharField(blank=True, help_text='Введите адрес в Яндекс.Картах', max_length=100, null=True)),
                ('google_maps', models.CharField(blank=True, help_text='Введите адрес в Google Maps', max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.dopeuser')),
            ],
            options={
                'verbose_name_plural': 'Maps',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Gaming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitch', models.CharField(blank=True, help_text='Профиль Twitch', max_length=100, null=True)),
                ('steam', models.CharField(blank=True, help_text='Профиль Steam', max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.dopeuser')),
            ],
            options={
                'verbose_name_plural': 'Gaming',
                'ordering': ['user'],
            },
        ),
    ]
