# Generated by Django 3.2.5 on 2021-07-22 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_auto_20210722_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='maps',
            name='2GIS',
            field=models.CharField(blank=True, help_text='Введите координаты в 2ГИС', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='maps',
            name='address',
            field=models.CharField(blank=True, help_text='Введите адрес', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='gaming',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.dopeuser'),
        ),
        migrations.AlterField(
            model_name='maps',
            name='google_maps',
            field=models.CharField(blank=True, help_text='Введите координаты в Google Maps', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maps',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.dopeuser'),
        ),
        migrations.AlterField(
            model_name='maps',
            name='yandex_maps',
            field=models.CharField(blank=True, help_text='Введите координаты в Яндекс.Картах', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='messengers',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.dopeuser'),
        ),
        migrations.AlterField(
            model_name='musicplatforms',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.dopeuser'),
        ),
        migrations.AlterField(
            model_name='other',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.dopeuser'),
        ),
        migrations.AlterField(
            model_name='personalcontacts',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.dopeuser'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.dopeuser'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.dopeuser'),
        ),
        migrations.AlterField(
            model_name='videocallservices',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.dopeuser'),
        ),
        migrations.AlterField(
            model_name='videohostings',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.dopeuser'),
        ),
        migrations.AlterField(
            model_name='wallets',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.dopeuser'),
        ),
        migrations.AlterField(
            model_name='wallets',
            name='yoomoney',
            field=models.CharField(blank=True, help_text='Укажите номер кошелька YooMoney (Яндекс.Деньги)', max_length=100, null=True),
        ),
    ]
