# Generated by Django 3.2.5 on 2021-07-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_auto_20210722_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='github',
            field=models.CharField(blank=True, help_text='Профиль GitHub', max_length=100, null=True),
        ),
    ]
