# Generated by Django 3.2.5 on 2021-07-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0014_portfolio_github'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallets',
            name='yoomoney',
            field=models.CharField(blank=True, help_text='Укажите номер кошелька YooMoney (Яндекс.Деньги)', max_length=100, null=True, verbose_name='YooMoney'),
        ),
    ]
